### ISSUE TITLE
Code improvements meta issue

### ISSUE THREAD

**Issue by monfera** [elastic/elastic-charts#1303]
- [ ] Check for zero dimension canvas mentioned at the bottom of [this](https://github.com/elastic/elastic-charts/pull/1286#discussion_r688151382) as otherwise the current code (pre or post merge) may throw
- [ ] Reconsider the [array enums](https://github.com/elastic/elastic-charts/pull/1286#discussion_r685358962) and object enums as the time for switching to proper TS enums may have come, and/or it's sometimes possible, and better, to piggyback on a preexisting HTML DOM type library instead of explicitly listing values (though the latter would help generate configuration UIs automatically, cf. `Config` object in partition charts) 
- [ ] (maybe for a separate, functiona meta issue?) More pattern filling options, eg. round number of tiling, or constrained, approximate tile sizes (in pixels) as well as scaling options upon resize (initial [discussion](https://github.com/elastic/elastic-charts/pull/1286#discussion_r688138312))
- [ ] Consider renaming`ON_TOGGLE_DESELECT_SERIES` ([comment](https://github.com/elastic/elastic-charts/pull/1273#discussion_r689314258))
- [ ] Consider moving away from the use of `specId` in heatmap to encode information (came up eg. [here](https://github.com/elastic/elastic-charts/pull/1273#commitcomment-54945011))
