### ISSUE TITLE
Better generics for data and events

### ISSUE THREAD

**Issue by rshen91** [elastic/elastic-charts#1380]
**Is your feature request related to a problem? Please describe.**
Limit the use of unions throughout charts in cases like onBrushEnd.

- [ ] Data - determine what type of chart with just data passed in
- [ ] Events - union event such as in onBrushEnd between XY and Heatmap

**Describe the solution you'd like**
There can be a generic provided in the Settings component instead of using union types throughout

**Additional context**
#1369 has some discussion https://github.com/elastic/elastic-charts/pull/1369#discussion_r707357758

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues/feature requests here.

**Checklist**

Delete any items that are not applicable to this feature request.

- [ ] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present
