### ISSUE TITLE
Playwright e2e migration

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1577]
# Summary

This issue is to track the migration of out vrt runner to [playwright](https://playwright.dev/).

## Tasks

- [x] Refactor CI to accommodate running playwright on GH actions with deployed instance
- [x] Copy old tests to future home under the new playwright system (#1573)
- [ ] Migrate all supporting code from puppeteer api to playwright
- [ ] Migrate testing code from puppeteer api to playwright
- [ ] Setup local playwright runner under same scripts as today (e.g. `test:integration[:*]` to `test:e2e[:*]`)
- [ ] Update vrt screenshots using new playwright workflow
- [ ] Confirm CI stability

## Future optimizations
- [ ] Create fallback flow if deployment fails to load archive `e2e-server` files.
- [ ] Create scheduled CI cleanup tasks to tear down environments and firebase channels.
- [ ] Upload test failure files to GCP cloud storage
- [ ] Migrate CI to buildkite

**Comment by markov00** [comment]
@nickofthyme could you please update the various lists? I think we can mark some items as done already

**Comment by nickofthyme** [comment]
Closed by https://github.com/elastic/elastic-charts/pull/1572 & https://github.com/elastic/elastic-charts/pull/1733
