### ISSUE TITLE
Metric + micro combo visualization

### ISSUE THREAD

**Issue by ryankeairns** [elastic/elastic-charts#1578]
**Describe the solution you'd like**
To make metric visualizations more impactful, we would like to convey additional information while also ratcheting up the visual prominence. For example, it is not uncommon to find metric + chart combinations in other offerings that look something like:

![Micro Visualizations](https://user-images.githubusercontent.com/18484576/142194076-304fb60e-9fbb-43cb-8cf0-ed85ad8e7f7c.jpg)

<img width="982" alt="Screen Shot 2022-02-02 at 3 53 52 PM" src="https://user-images.githubusercontent.com/446285/152243746-4686d8d4-420f-43ed-bf52-d35e46280fd8.png">

**Describe alternatives you've considered**
There have been some recent enhancements to the basic design elements by [filling the background](https://github.com/elastic/kibana/pull/122091) and providing [text alignment options](https://github.com/elastic/kibana/pull/124124), but we would like to take this notion further. 

**Additional context**
This request is originating from the [dashboard audit](https://github.com/elastic/kibana/issues/118429#issuecomment-971587718) which @gvnmagni performed recently.

**Kibana Cross Issues**
[[Dashboard] [META] Aesthetic by default](https://github.com/elastic/kibana/issues/118429#)

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by ryankeairns** [comment]
I'm getting the drift that metric visualizations (as provided by Lens) are not of Elastic Charts rather are simple text objects.

That said, this combo visualization type is still desirable. Let me know if I should take another approach!

**Comment by markov00** [comment]
Hi @ryankeairns moving metric visualization within our repo is definitely something that we are planning and thanks for opening the issue here. Moving that viz to the chart repo can help us aligning the API, the style and the behaviour when using, for example, small multiples

**Comment by ghudgins** [comment]
A few requirements we're surfacing on the Kibana side in planning today. Documenting them here although we likely would want to create issues for some of them at some point: 

 - for the non-time combo visualization: ability to specify min value / max value (might be worth knowing if goal value is good for this visualization or if it only makes sense for bullet style gauges)
 - small multiples: add break down for metric visualization. Investigate options around layout options (both grid choices and other shapes)
