### ISSUE TITLE
Buildkite CI improvements

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1617]
## Future enhancements

- [x] Create foundation of buildkite CI https://github.com/elastic/elastic-charts/pull/1733
- [x] Remove obsolete code and configurations https://github.com/elastic/elastic-charts/pull/1803
- [ ] git clone with `depth 1` to avoid downloading the full repo [see here](https://forum.buildkite.community/t/shallow-clones/282/3) 
- [ ] Enable better caching see [link](https://github.com/gencer/cache-buildkite-plugin)
- [ ] Configure our own agents. Currently we are using a small instance from kibana that is suitable to all our jobs. But the wait times for these are between 1m and >3m for the job to even start, even with the job `priority` set very high. Not using our own agents also limits our ability to cache things specific to charts. I don't think this is a huge issue for the time being but should be considered later.
- [ ] Optimize the buildkite upload script (see [example run](https://buildkite.com/elastic/elastic-charts-ci/builds/233#0f52a661-1f12-414b-b31c-5680da99554f)). This script, like all others, takes several minutes (~3) to wait, start and finish running. This is creates incredible flexibility for dynamic pipelines but blocks all other jobs from even starting. Having our own agent pool would help this.
- [ ] Verify the reason why every job has a `installing npm modules` as part of their last command. In particular the Firebase deploy has a very long 1.4 minutes node module install process https://buildkite.com/elastic/datavis-ci/builds/646#_
- [ ] expose logs at github level or link directly the status of a PR to the buildkite without passing for github
- [ ] show the total CI time testing time on the PR message
- [ ] When requesting to update the screenshot from a GH comment, just rerun the minimal required tasks

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
