### ISSUE TITLE
Flame: chart protocol completion and other todo

### ISSUE THREAD

**Issue by monfera** [elastic/elastic-charts#1671]
Chart protocol:
- [ ] debug DOM data generation
- [ ] accessibility layer generation
- [ ] signaling of chart rendered

Interactions / examples:
- [ ] placement and design for affordances (reset, search, direct manipulation interaction modifier keys)
- [ ] reset (via input/callback eg. for a reset button)
- [ ] text/regex search facility
- [ ] keyboard navigation and accessibility
- [ ] focus rectangle: move, move border, resize on minimap
- [ ] box select and focus (horizontal, vertical, both) on focus layer

Chart configurability
- [ ] actually make use of the `valueFormatter` in the charts API
- [ ] make use of the font family from the charts theme

Cross platform / browser
- [ ] triage the Ubuntu render issue mentioned by @thomasdullien (we've been awaiting further info/collab on it as we have no issue reproduction yet)
- [ ] Cross-browser issues: big browser/pinch zoom disappearance (FF, Safari); vertical zoom jumpy text length (Safari)

Arising from https://github.com/elastic/elastic-charts/pull/1664
