### ISSUE TITLE
[meta] Metric Improvements

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1704]
- [ ] #1705
- [ ] Add interaction (click/hover)
- [ ] Add title/subtitle padding at `m` and `l` breakpoints

Nice to have
- [ ] Improve responsiveness (compute text height based on content)
