### ISSUE TITLE
TSVB cross issues checks

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#178]
This meta issue will keep tracks on the existing Kibana TSVB issues and what can be solved replacing that chart with elastic-charts.

**Kibana Cross Issues**

- [x] https://github.com/elastic/kibana/issues/17541
- [ ] https://github.com/elastic/kibana/issues/14799
- [x] https://github.com/elastic/kibana/issues/28178
- [x] https://github.com/elastic/kibana/issues/19471
- [x] https://github.com/elastic/kibana/issues/16431
- [x] https://github.com/elastic/kibana/issues/15543
- [x] https://github.com/elastic/kibana/issues/42378
- [x] https://github.com/elastic/kibana/issues/42785

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by timroes** [comment]
cc @sulemanof In case you're not aware of this, it would be super if we could check the above list when close to merging the TSVB elastic chart PR, if the above issues are closed by that PR (and if so let's link them into the PR).

**Comment by markov00** [comment]
Closing this meta issue, all issues are covered except for the performance one that is not probably fully tested in Kibana TSVB environment.
If performance is an issue, please open a new issue
