### ISSUE TITLE
Flamegraph Fixes

### ISSUE THREAD

**Issue by timductive** [elastic/elastic-charts#1806]
**Describe the issue**

- [ ] [Mini-flamegraph view is flickering](https://github.com/elastic/prodfiler/issues/2516)
- [ ] [Traverse by relevance instead of by left<>right](https://github.com/elastic/prodfiler/issues/2551)
- [ ] [Flamegraph renders incorrectly when updating timerange](https://github.com/elastic/elastic-charts/issues/1766)
