### ISSUE TITLE
Use elastic-charts in Kibana Discover

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#191]
**Is your feature request related to a problem? Please describe.**
Additional features needed in elastic-charts:
- [x] `DONE` BarSeriesSpec needs to have a "histogram mode" for positioning ticks correctly (PR #218)
![image](https://user-images.githubusercontent.com/452850/58044656-2eaa4e00-7af5-11e9-8820-0727a71b5bb0.png)
  - [x] ticks should be aligned to the starting edge of a bar and bars cannot be clustered (only stacked)
  - [x] xDomain annotation positions should be aligned correctly (currently they snap to a band edge)
- [x] `DONE` customizable tooltip content (PR #233)
  - [x] need to be able to add x-axis title to chart tooltip (formatter for tooltip header)
  - [x] need to be able to add message about partial bucket to chart tooltip (additional information iff match for filter value)
- [x] `DONE` in histogram mode, need to extend line annotation (PR #236)
- [x] `DONE` check bucket sizing in histogram mode, at some time intervals, buckets appear much larger (PR #240)
- [x] `DONE` ticks in histogram mode need to be extended correctly (PR #251 )
- [x] `DONE` single datum tooltip bug (PR #259)
- [x] `DONE` show `now` line annotation in single datum yearly view (PR #265)

On the Kibana side: 
- [x] `IN PROGRESS` Use elastic-charts component (https://github.com/elastic/kibana/pull/43788)
  - [x] Partial bucket rect annotations 
  - [x] Partial bucket custom tooltip header
  - [x] Line annotation for current time
  - [x] Axis ticks line up correctly for each time interval
  - [x] Buckets render correctly for each time interval
    - [x] check all ranges at auto interval
    - [x] check all ranges at manually set intervals
  - [x] On brush, fetch new data
  - [x] styling (we will use the elastic-charts theme defaults but should check both dark & light modes)
  - [x] fix tests [note updating with elastic-charts did not break any tests]
  - [x] line annotation for `now` renders correctly
    - [x] within chart when now is within time range
    - [x] adjust position to make line visible when at domain edge
  - [x] localize custom text
  - [x] rect annotation tooltip should be formatted correctly
  - [x] y-axis formatter
  - [x] bug when hovering out of tooltip

**Describe the solution you'd like**
Use elastic-charts for the charts in Kibana Discover.

**Describe alternatives you've considered**

**Additional context**

**Kibana Cross Issues**
TODO

**Checklist**

- [x] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by emmacunningham** [comment]
A couple of things to discuss: 
- y axis formatter when counts are < 0 (when interval is very low)
- yearly view, e.g.:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/452850/60498518-95ca2f00-9c6b-11e9-87d6-52555977f3ed.png">
- should we write tests for the histogram component?

**Comment by emmacunningham** [comment]
Follow-up from elastic-charts sync:

- y axis formatter when counts are < 0 (when interval is very small - milliseconds or seconds)
the current implementation formats all values below 0 as `0` which is not very useful.  the group's consensus is that the elastic-charts handling (rendering the much more detailed decimal values) is the correct one and also that getting to these views is in and of itself odd.

- should we write tests for the histogram component?
no because there currently are no tests for the component and as things in discover are changing quickly, the effort outweighs the gains.  we will write no new additional tests.

- yearly, monthly, and weekly manual intervals:
the elastic-charts bucket sizes are correct and there appears to be an issue with the current implementation (see above screenshots).  as for the yearly view, this is a weird case to begin with (we may want to disable the user's ability to select this for date ranges that are too small).  at any rate, the group agreed that the elastics-charts bucket size for these larger ranges is correct and we will follow up on the kibana side to better enforce the interval options.

**Comment by markov00** [comment]
close as Kibana Discover is already using elastic-charts since 7.5
