### ISSUE TITLE
Roadmap (phase 1)

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#2]
The below is a list of near term items planned for the first release on February 2019.

---

### Paddings/Margins
- [x] Add chart padding
- [x] Add data padding between chart and axis (a configurable padding of the chart elements and the axis

### Scales
- [x] Add time scale (see limitations)
- [x] Merge scales with multiple series depending on grouping (phase 1: basic merging, no stacking controls/rendering order)
- [x] Add custom X domain for series (enable the dev to add it’s own domain extents to control the visualization)
- [x] Fix computeOrdinalDataDomain in domain.ts sort by uniq value: add comparator
- [x] Check when adding one or more split series, transform the x axis from linear/time to ordinal
- [x] Compute the right band width for a linear/time scale type
- [x] Check if 0 split series are used, than use the original x scale type (linear, time etc)
- [x] Transform ordinal scales into linear scales to compute less number of ticks when possible (our current ordinal scale compute all ticks dimensions for each element in the domain, if the dataset x value can be converted into a linear scale, it’s better to convert back to linear before computing ticks to optimise axis computation)
- [x] Fix ordinal scales rendering with multiple data series

### Colors
- [x] Add basic colors to bar charts (define what is the policy behind colouring)
- [x] Merge colour scales: when using more than one series type (bar + line) manage the colors together
- ~[ ] Add external custom colour from spec props~ (moved to phase 2)

### Axis
- [x] Set max axis extent
- [x] Rotate labels
- [x] Horizontal / vertical grids
- ~[ ] Configure axis label max width/height as multiple of EUI sizes~ (moved to phase 2) (#40)

### Charts
- [x] Add opaque non stacked bar/area charts
- [x] Add curves to lines and areas
- [x] Add bar series chart
- [x] Add area chart
- [x] Add line chart
- [x] Add stacked area charts
- [x] Add stacked line charts
- [x] Renderer multiple type charts
- ~[ ] Handle negative values in stacked area charts~ (moved to phase 2)
- [x] Add test with 3 or more stacked areas
- ~[ ] Add z-index to each series~ (moved to phase 2)

### Interaction/Animation
- [x] Add interactions (tooltip)
- [x] Add animations
- [x] Add background rect to each interval to enable the highlight
- [x] Add hover interaction to line charts
- [x] Add hover interaction to area charts 
- [x] Add brush/selection tool (check if the selection be discrete and relative to the main X axis value. Keep the brush tool independent from the elements on the chart aka drag from everywhere)
- ~[ ] Add color to tooltip value~ (moved to phase 2)

### General
- [x] Implement chart rendering in canvas (konva)
- [x] Implement first version of chart in Canvas
- [x] Chart rotation 90 degree
- [x] Chart rotation -90 degree
- [x] Chart rotation 180 degree
- [x] Expose the chart rotation props to a generic Settings component
- [x] Add chart theming options
- [x] Refactor axis dimension computation to accommodate the new format of series/domains
- [x] Remove unnecessary code of the old bar, line, area rendering
- ~[ ] Add a direct render in konva native, without the use of React to increase performance.~ (moved to phase 2)
- ~[ ] Fitting functions elastic/kibana#17717~ (moved to phase 2)(PR #55)
- ~[ ] Fix yScaleToDataExtent: some bars are overflowing the chart~ (moved to phase 2)
- [x] Check performances (build, animate and update 1 high density chart, multiple small density charts, multiple medium density charts)

### Legends
- [x] Add legend component
- ~[ ] Add hover/click event for each legend series~ (moved to phase 2) (PR #51)
- ~[ ] Add color picker for each legend series~ (moved to phase 2)

**Comment by markov00** [comment]
Closing as the deadline was reached. Missing tasks were moved to [phase 2](#3)
