### ISSUE TITLE
[Meta] Reclaim chart theme from eui

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#2069]
Per discussions from #865, we have determined to go ahead with moving the charts theme from [eui](https://github.com/elastic/eui/blob/main/src/themes/charts/themes.ts#L215) back to charts.

# Action items for EUI

## Font family

Resolve which font family to use for charts theme? Currently the eui charts theme 
defines the `fontFamily` [here](https://github.com/elastic/eui/blob/8992deb683199b772569de59f701068d765c17cf/src/themes/charts/themes.ts#L17-L18) as...

```ts
const fontFamily = `'Inter', 'Inter UI', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'`;
```

but the eui theme JSON defines three font families as...

```jsonc
{
  ...
  "font": {
    "family": "'Inter', BlinkMacSystemFont, Helvetica, Arial, sans-serif",
    "familyCode": "'Roboto Mono', Menlo, Courier, monospace",
    "familySerif": "Georgia, Times, Times New Roman, serif",
    ...
    }
 }
```

I assume for charts we want to use `theme.font.family`, needs confirmation.

## Export colors

Export computed theme colors [here](https://github.com/elastic/eui/blob/8992deb683199b772569de59f701068d765c17cf/src/themes/charts/themes.ts#L212-L213) to either the theme JSON or a separate colors-only JSON distributable for dark and light themes.

# Action items for charts

## Update existing charts theme

Update the charts theme to conform to the current eui chart theme defaults found [here](https://github.com/elastic/eui/blob/8992deb683199b772569de59f701068d765c17cf/src/themes/charts/themes.ts#L25-L206). This includes importing the colors and `fontFamily` from eui JSON and/or palette functions. Also need to append the colors with `chartLines` and `chartBand` defined per theme [here](https://github.com/elastic/eui/blob/8992deb683199b772569de59f701068d765c17cf/src/themes/charts/themes.ts#L215-L225C4). 

## Final logistical steps

- [x] Release charts version with new themes.
- [x] Update charts in kibana.
  - Verify changes to theme with all stakeholders in kibana.
  - Remove eui chart theme logic. Could simply replace theming first and simplify chart theme service later.
- [x] Remove chart theming from eui, update eui in kibana. https://github.com/elastic/eui/pull/7572
- [x] Update PR template action referring to theme changes.
- [x] Update storybook to test only new themes and remove logic for eui theme support.

# Future tasks

## Handle dynamic theme changes

Possibly by creating a global charts provider in kibana to update theming based on changes to `EuiProvider` base theming.

## Migrate away from eui sass

Charts currently relies on several sass files from eui (see [`_eui_imports.scss`](https://github.com/elastic/elastic-charts/blob/3b8243c8222fc335670cf77b2013aadf9e7dcc7a/packages/charts/src/_eui_imports.scss)) to match basic styles from eui. These include variables, functions and mixins.

Need to **discuss** how to resolve this - possible options are:
- Duplicate functionality in charts.
- Use custom chart styles to get _close_.
- Somehow use eui emotion styles in charts (Migrate chart styles to pure javascript).

**Comment by markov00** [comment]
not yet, there are a few steps more to complete this

**Comment by nickofthyme** [comment]
Sorry @stratoula,

Yes after merging https://github.com/elastic/kibana/pull/170914 we can close this. All we need to do after is remove the chart theme logic from eui and eventually remove the deprecated themes from charts down the road.

**Comment by nickofthyme** [comment]
Yup will do!

**Comment by nickofthyme** [comment]
Closing with merging https://github.com/elastic/eui/pull/7572

**Comment by nickofthyme** [comment]
Finally removing all theme export from eui in https://github.com/elastic/eui/pull/7682. Finishes this issue in full.
