### ISSUE TITLE
Value label improvements

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#2155]
A collection of issues related to the value label on bars, area and line charts.

```[tasklist]
### General value label issues
- [ ] https://github.com/elastic/elastic-charts/issues/454
- [ ] https://github.com/elastic/elastic-charts/issues/792
- [ ] https://github.com/elastic/elastic-charts/issues/856
```

```[tasklist]
### Bar value label issues
- [ ] https://github.com/elastic/elastic-charts/issues/635
- [ ] https://github.com/elastic/elastic-charts/issues/2092
```

```[tasklist]
### Line/Area value label issues
- [ ] https://github.com/elastic/elastic-charts/issues/797
```
