### ISSUE TITLE
Chart Restyle

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#232]
## General:

- [x] `IN REVIEW` #317 Multiple way to set the`<Chart />` size
- [x] `IN REVIEW` #320 Remove clipping regions https://github.com/elastic/elastic-charts/issues/20
- [ ] Reorder color palette to avoid having vibrant colors one near the other
- [ ] https://github.com/elastic/elastic-charts/issues/1276

## Bar chart:

- [ ] Rounded corners (border-radius) for bars, configurable via theme and also specific bar style with few options: flat, rounded on edges (top and bottom), all rounded (each bar has rounded corners), round on top (default). The radius is configurable in px and %.
- [ ] Configurable outer padding of the chart https://d.pr/free/i/5FVNo6
- [ ] Configurable padding between clustered bars https://d.pr/free/i/lkgsj5

## Line chart:

- ~[ ] Curve default to a smooth one https://github.com/elastic/elastic-charts/issues/121~
- [ ] Hide point markers when the space between points is too small to see the twist and turn of the line

## Area chart:
- ~[ ] Curve default to a smooth one https://github.com/elastic/elastic-charts/issues/121~
- [ ] Check the possibility to add a gradient on the fill

## Axis/Grids
- [x] `DONE` #314 Remove spaces around chart/labels if padding or size is 0 https://d.pr/free/i/5iUHSH
- [x]  `DONE` #314  Reduce the chart size if the edge labels are overflowing the chart size 
- [x] `IN REVIEW` #319 Allow set the number of ticks for each axis
- [ ] (extra) It would be nice to be able to just display axes and grid without the need to add a chart type.
- [ ] Can the time formatter be smarter about not needing to show certain parts of the timestamp if they're always the same across the axis? https://d.pr/free/i/WkkiZN https://d.pr/free/i/tMVbqN

## Interactions
- [ ] Enable custom hover effect on bars/pints
- [ ] Enable cursor pointer only if there are callback associated
- [ ] Shaded column for line charts https://d.pr/free/i/JmZl7a

## Tooltip
- [ ] Add total for stacked value tooltips (this can be in the [header of the tooltip](https://d.pr/free/i/VIY9iZ))
- [ ] Fix tooltip to the top (no horizontal movement)
- [ ] Fix tooltip for long text/values
- [ ] When there's only one series, no need to show the name of the series in the tooltip https://d.pr/free/i/k0UuRI

## Annotations
- [x] Align annotation icon to the top if possible
<img width="441" alt="118sKtg3RBhE6pYZfW_udOSV71u5PSDC8KLTmhWo" src="https://user-images.githubusercontent.com/1421091/59255152-d5d06000-8c31-11e9-9abb-38f07b1d0e0e.png">

## Legend
- [x] `IN PROGRESS` #321 When hovering on a legend item that is currently hidden, don't fade the other series https://d.pr/free/i/DbbyWC
- [x] When **not** hovering on the chart, allow the legend values to be the **total** value instead of the last x value. https://d.pr/free/i/1D9Bw3

## Themes

- [ ] Better default style colors

**Comment by markov00** [comment]
@cchaos regarding
> When not hovering on the chart, allow the legend values to be the total value instead of the last x value. https://d.pr/free/i/1D9Bw3

This is not the default behaviour in TSVB, TSVB will always shows the last bucket value.  We can hide that value by default, and we will find a different way to  configure what will represent that number.

**Comment by abdul737** [comment]
Is it currently possible to add a gradient to the AreaSeries, like in this design?:   
![image](https://user-images.githubusercontent.com/17930041/79344299-14693200-7f49-11ea-8dea-d0afc35658b6.png)

**Comment by markov00** [comment]
@abdul737 we have a list item for that in this ticket and we are going to support that, but it's currently not on our immediate priority list.

**Comment by markov00** [comment]
closing this for now, most of the tasks are in place, others need to be reconsidered.
