### ISSUE TITLE
[meta] Axis and labels

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#2320]
Collecting all the axis and label related issues

- [ ] https://github.com/elastic/elastic-charts/issues/40
- [ ] https://github.com/elastic/elastic-charts/issues/313
- [ ] https://github.com/elastic/elastic-charts/issues/369
- [ ] https://github.com/elastic/elastic-charts/issues/396
- [ ] https://github.com/elastic/elastic-charts/issues/452
- [ ] https://github.com/elastic/elastic-charts/issues/676
- [ ] https://github.com/elastic/elastic-charts/issues/753
- [ ] https://github.com/elastic/elastic-charts/issues/761
- [ ] https://github.com/elastic/elastic-charts/issues/778
- [ ] https://github.com/elastic/elastic-charts/issues/889
- [ ] https://github.com/elastic/elastic-charts/issues/891
- [ ] https://github.com/elastic/elastic-charts/issues/915
- [ ] https://github.com/elastic/elastic-charts/issues/1008
- [ ] https://github.com/elastic/elastic-charts/issues/1157
- [ ] https://github.com/elastic/elastic-charts/issues/1168
- [ ] https://github.com/elastic/elastic-charts/issues/1179
- [ ] https://github.com/elastic/elastic-charts/issues/1188
- [ ] https://github.com/elastic/elastic-charts/issues/1217
- [ ] https://github.com/elastic/elastic-charts/issues/1311
- [ ] https://github.com/elastic/elastic-charts/issues/1442
- [ ] https://github.com/elastic/elastic-charts/issues/1490
- [ ] https://github.com/elastic/elastic-charts/issues/1492
- [ ] https://github.com/elastic/elastic-charts/issues/1586
- [ ] https://github.com/elastic/elastic-charts/issues/1587
- [ ] https://github.com/elastic/elastic-charts/issues/1606
- [ ] https://github.com/elastic/elastic-charts/issues/1640
- [ ] https://github.com/elastic/elastic-charts/issues/1701
- [ ] https://github.com/elastic/elastic-charts/issues/1840
- [ ] https://github.com/elastic/elastic-charts/issues/1877
- [ ] https://github.com/elastic/elastic-charts/issues/1923
- [ ] https://github.com/elastic/elastic-charts/issues/1925
- [ ] https://github.com/elastic/elastic-charts/issues/1925
- [ ] https://github.com/elastic/elastic-charts/issues/1934
- [ ] https://github.com/elastic/elastic-charts/issues/1926
- [ ] https://github.com/elastic/elastic-charts/issues/1952
- [ ] https://github.com/elastic/elastic-charts/issues/2123
- [ ] https://github.com/elastic/elastic-charts/issues/2125
- [ ] https://github.com/elastic/elastic-charts/issues/2126
- [ ] https://github.com/elastic/elastic-charts/issues/2130
- [ ] https://github.com/elastic/elastic-charts/issues/2207
- [ ] https://github.com/elastic/elastic-charts/issues/2236
- [ ] https://github.com/elastic/elastic-charts/issues/2304
- [ ] https://github.com/elastic/elastic-charts/issues/2307
- [ ] https://github.com/elastic/elastic-charts/issues/2311
