### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#3]
### Replaced by the [DataVis plan project](https://github.com/elastic/elastic-charts/projects/14). Please refer to that project for an updated roadmap

*The version numbers in this issue reflect version numbers of Kibana releases, at which we're planning to have the functionality implemented in Elastic charts. They are not reflecting actual Elastic Chart version numbers.*

<details>
<summary><strong>Kibana 7.2</strong></summary>

- [x] `DONE` Preparation for TSVB timeseries chart replacement #64 
    - [ ] ~~`IN PROGRESS` Replacement of TSVB timeseries chart (EPAM) #108~~ `moved to 7.3`
    - [x] `DONE` Series specific styling (line width, opacity) #138 PR #170 
    - [x] `DONE` Handle band area charts (used on percentile band mode) #144 PR #157 
    - [x] `DONE` Add last bucket value on the legend #143 PR #155
    - [x] `DONE` Fix for time scales in different time zones #130 PR#151
    - [x] `DONE` Handle/Test negative values in stacked area charts  #135 PR #149 
    - [x] `DONE` Add annotation line #81 PR #126 
    - [x] `DONE` hide in legend (hide that series from the legend) #137 PR #147 
    - [x] `DONE` Add a separated name props on each series #136 PR #142
    - [x] `DONE` Display orphan data points on line/area series #63 PR #114
    - [x] `DONE` [Add external custom colour from spec props](#39) #39 PR #95
    - [x] `DONE` Crosshair and vertical/horizontal cursors #80 #58  PR #96
    - [x] `DONE` Scale data to specific domain #86 PR #98
    - [x] `DONE` Add filter in/out series only action to listeners) PR #51
    - [x] `DONE` Add hide/show series chart internals) PR #51
    - [x] `DONE` Add hover/click event for each legend series PR #51
    - [x] `DONE` Add color picker for each legend series #23 PR #51
- [x] Preparation for Discovery chart replacement
    - [ ] ~~`IN PROGRESS` Replacement of the chart #191~~ `moved to 7.3`
    - [x] `DONE` Add annotation rects #105 PR #180 
- [x] `DONE` Value labels option for charts without hovering #67  PR #182
- [ ] ~~Visual regression tests #77~~ `moved to 7.3`
- [ ] ~~Avoid clipping tooltip markers on edges #20~~ `moved to 7.3`
</details> 

<details>
<summary><strong>Kibana 7.3</strong></summary>

- [ ] ~~`IN PROGRESS` Replacement of Discovery chart #191~~ `moved to 7.4`
- [ ] ~~`IN PROGRESS` Replacement  of TSVB timeseries chart (EPAM) #108~~ `moved to 7.4`
- [ ] ~~`IN PROGRESS` Pie chart #84~~ `moved to 7.4`
- [ ] ~~Preparation for Stack Monitoring chart replacement #65~~ `moved to 7.4`
    - [x] Crosshair and vertical/horizontal cursors #80
    - [x] Add annotation lines/rects #81
    - [ ] Sync crosshair/vertical cursor across charts #83
    - [x] Hovered value appears on legend item
- [ ] ~~Add configuration validation #85~~ `moved to 7.4`
- [ ] ~~Basic export as PNG function #82~~ `moved to 7.4`
- [ ] ~~Visual regression tests #77~~ `moved to 7.4`
- [ ] ~~Avoid clipping tooltip markers on edges #20~~ `moved to 7.4`

</details>

<details>
<summary><strong>Kibana 7.4</strong></summary>

- [ ] ~~`DONE` Replacement of Discovery chart~~ #191 `moved to 7.5`
- [ ] `UNDER REVIEW` Replacement  of TSVB timeseries chart (EPAM) #108 `moved to 7.5`
- [x] `DONE` Preparation for Stack Monitoring chart replacement #65
    - [x] `DONE` Sync crosshair/vertical cursor across charts #83
- [ ] ~~`IN PROGRESS` Pie chart~~ #84 `moved to 7.5`
- [ ] ~~Preparation for vislib chart replacement (#66)~~ `ON HOLD`
    - [ ] ~~Scatterplot~~
    - [ ] ~~Multiple charts/Split charts/Small Multiples~~
    - [ ] ~~Truncate labels to specific width~~
- [ ] ~~Heatmap~~ `moved to 7.5`
- [ ] ~~`IN PROGRESS` Add configuration validation #85~~ `moved to 7.5`
- [ ] ~~Basic export as PNG function #82~~ `moved to 7.5`
- [ ] ~~Visual regression tests #77~~ `moved to 7.5`
- [x] `DONE` Avoid clipping tooltip markers on edges #20
</details>

<details>
<summary><strong>Kibana 7.5</strong></summary>

- [x] `DONE` Replacement  of TSVB timeseries chart (EPAM) #108
- [x] `DONE` Replacement of Discovery chart #191
- [x] `DONE` Visual regression tests #77
- [ ] ~~`IN PROGRESS` Pie chart #84~~ `moved to 7.6`
- [ ] ~~Heatmap~~ `moved to backlog`
- [ ] ~~a11y~~ `moved to 7.6`
- [ ] ~~Basic export as PNG function #82~~ `moved to 7.6`
- [ ] ~~Preparation for vislib chart replacement (#66)~~ `moved to backlog`
</details>

# Kibana 7.6
- [x] `DONE` Pie chart #84
- [x] `DONE` Basic export as PNG function #82
- [x] `DONE` Moving from MobX to Redux #281
- [ ] `PAUSED` Add configuration validation #85
- [ ] ~~Accessibility #300~~ `moved to 7.9`

# Kibana 7.7
- [x] `DONE` add pie chart events listeners (#578)
- [x] `DONE` add pie chart tooltip (#544)
- [x] `DONE` add percentage in piechart/treemap (#558) 
- [x] `DONE` Gauge([/ɡāj/](https://www.google.com/search?q=gauge&oq=gauge&aqs=chrome..69i57j0l7.1400j0j7&sourceid=chrome&ie=UTF-8))/Goal chart type (https://github.com/elastic/elastic-charts/issues/520)
- [x] `DONE`  add pie chart legend
- [ ] `IN PROGRESS` vislib replacement (features: #502)

# Kibana 7.8

# Kibana 7.9
- [ ] `IN PROGRESS` vislib replacement (features: #502)
- [ ] split charts/ trellis / small multiples #500
- [ ] Heatmap #501
- [ ] Accessibility #300 
- [ ] *Tag cloud*
- [ ] *vislib replacement*

# Kibana 8
- [ ] scatterplot + sankey
- [ ] *WebGL (high number of data points)*
- [ ] *Animations*

# Backlog

### Axis
- [ ] Configure axis label max width/height as multiple of EUI sizes (issue #40)
- [ ] Add multilevel axis (shows axis on sub/aggregations) ([similar to](https://github.com/datavisyn/chartjs-scale-hierarchical))

### Charts
- [ ] Add padding between bar series clusters
- [x] Add z-index to each series
- [ ] Preparation for vislib chart replacement (#66)
    - [ ] Scatterplot #502 
    - [ ] Multiple charts/Split charts/Small Multiples #500
    - [ ] Truncate labels to specific width

### Interaction/Animation
- [x] Add color to tooltip value
- [ ] Test animations on data streams

### General

- [ ] Move theming from canvas to SVG
- [ ] Keep up to speed with SVG rendering
- [x] Add a direct render in konva native, without the use of React to increase performance
- [x] Fitting functions elastic/kibana#17717 (PR #55)
- [x] Fix yScaleToDataExtent: some bars are overflowing the chart

**Comment by markov00** [comment]
## Tasks moved from 7.2 to 7.3
- `IN PROGRESS` Replacement of Discovery chart #191
**reason**: it was started in 7.2, but we spend more time on fixing existing features on 7.2
- `IN PROGRESS` Replacement of TSVB timeseries chart #108  
**reason**: we miss some features along the road like disabling the color picker, stack only few series together etc)
- `STALLED`  Visual regression tests #77
**reason**: We started it and than dropped the work on visual regression to waiting until we move our CI completely to jenkins (we are ready now to work on that)
- `NOT STARTED`  Avoid clipping tooltip markers on edges #20

**Comment by markov00** [comment]
## Tasks moved from 7.5 to 7.6
- `IN PROGRESS` Pie chart #84
**reason**: the refactoring mobx-redux is taking a bit longer than expected. The pie chart implementation is almost ready but needs to be integrated.
 - `IN PROGRESS` Visual regression tests #77
**reason**: this is started just a week ago and needs git LFS integration + a bit more work on collecting the diffs on CI
-  a11y
**reason**: we didn't put any effort already on that
- `IN PROGRESS` Basic export as PNG function #82 
**reason**: Rachel just started working on it now

## Tasks moved from 7.5 to backlog
- Heatmap
**reason**: it's better to postpone new charts. We want to land the piechart first
- Preparation for vislib chart replacement #166 
**reason**: we don't have enough space for that right now

**Comment by markov00** [comment]
## Tasks moved from 7.6 to 7.7
- Accessibility #300
**reason**: the refactoring from mobx to redux tooks much more time than expected. Instead of rushing we prefer to work in a clean and stable manner before adding a new feature

**Comment by markov00** [comment]
Replaced by the [DataVis plan project](https://github.com/elastic/elastic-charts/projects/14)
