### ISSUE TITLE
[meta] Chart Replacement Progress

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#417]
## Kibana charts to replace
Meta issue to track desired chart replacements in Kibana

### SIEM
- [x] Fully switched to @elastic/charts

### KibanaApp
- [x] Discover
- [x] TSVB
- [x] Lens
- [x] Vislib (DataVis team is currently working on the replacement) https://github.com/elastic/elastic-charts/issues/66 https://github.com/elastic/kibana/pull/57584
- [x] Piechart
- [x] Wordcloud
- [ ] Gauge, Goal
- [x] Heatmap
- [ ] Timelion (flot)

### Canvas
- [ ] `IN PROGRESS`  Currently using flot, the switch is currently WIP https://github.com/elastic/kibana/issues/41714

Ingest Management
- [ ] Fleet/DonutChart

### Discover
- [x] Main discover time histogram chart ([link](https://demo.elastic.co/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'filebeat-*',interval:auto,query:(language:kuery,query:''),sort:!('@timestamp',desc)))) #191 https://github.com/elastic/kibana/pull/43788

### Visualize
- [x] TSVB timeseries chart ([link](https://demo.elastic.co/app/kibana#/visualize/edit/bcb63b50-4c89-11e8-b3d7-01146121b73d?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-10-07T08:46:23.505Z',to:'2019-10-14T01:00:00.000Z'))&_a=(filters:!(),linked:!f,query:(language:kuery,query:''),uiState:(),vis:(aggs:!(),params:(annotations:!((color:'rgba(0,98,177,1)',fields:'FlightDelay,Cancelled,Carrier',icon:fa-exclamation-triangle,id:'53b7dff0-4c89-11e8-a66a-6989ad5a0a39',ignore_global_filters:1,ignore_panel_filters:1,index_pattern:kibana_sample_data_flights,query_string:'FlightDelay:true%20AND%20Cancelled:true',template:'%7B%7BCarrier%7D%7D:%20Flight%20Delayed%20and%20Cancelled!!',time_field:timestamp)),axis_formatter:number,axis_position:left,axis_scale:normal,id:'61ca57f0-469d-11e7-af02-69e470af7417',index_pattern:kibana_sample_data_flights,interval:%3E%3D1h,legend_position:bottom,series:!((axis_position:right,chart_type:line,color:'rgba(0,156,224,1)',fill:0.5,formatter:percent,id:'61ca57f1-469d-11e7-af02-69e470af7417',label:'Percent%20Delays',line_width:'2',metrics:!((id:'61ca57f2-469d-11e7-af02-69e470af7417',numerator:'FlightDelay:true',type:filter_ratio)),point_size:'0',separate_axis:0,split_mode:everything,stacked:none)),show_grid:1,show_legend:1,time_field:timestamp,type:timeseries),title:'%5BFlights%5D%20Delays%20%26%20Cancellations',type:metrics)))) #108 https://github.com/elastic/kibana/pull/33558

### Watcher UI
- [x] Watcher alert threshold

### Observability Metrics
- [ ] Log_minimap
- [ ] `IN PROGRESS` Replace Rhythm Charts with Elastic Charts https://github.com/elastic/kibana/pull/45114

### Observability Uptime
- [x] DonutChart

### Observability APM
- [ ] `IN PROGRESS` replacing react-vis

### ML
- [ ] TimeSeries explorer / timeseries chart
- [ ] Explorer charts
- [x] Swimlane (when heatmap will be available)

**Comment by nickofthyme** [comment]
I think this tracking is no longer needed
