### ISSUE TITLE
Renaming and type changes

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#495]
There is a branch of fixes on namings that we can apply but requires a breaking change.
I'd like to list them here so we can change them in one time for all
- [ ] `Position` -> proposed `Alignment` https://github.com/elastic/elastic-charts/pull/491#discussion_r357047994
- [ ] `Rotation` -> proposed `RotationDeg`, `AxisAlignedRotationDeg` https://github.com/elastic/elastic-charts/pull/491#discussion_r357040126
- [ ] `Rendering` -> `RenderTarget` , `RenderingSubstrate` https://github.com/elastic/elastic-charts/pull/491#discussion_r357365271
- [ ] `Color` -> `string | {rgb} | [rgb]` https://github.com/elastic/elastic-charts/pull/491#discussion_r357365597
