### ISSUE TITLE
Migrate stories source to Docs

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#498]
Let's remove the deprecated Storybook `addon-info` and let's start moving our story sources to Storybook Docs. 

Let's move our stories to the CSF https://storybook.js.org/docs/formats/component-story-format that is the new format adopted in 5.2 to document stories.

I think we should show a simple static example of each story source in the Docs page instead of the compiled code from the story itself. We should check how we can do that without duplicate too much code between the docs and the story example.

We should check that the props table is correctly rendered with all the props and their jsdocs.

## Tasks
- [ ] POC the CSF format for a small set of stories
- [ ] POC of the Docs (show source + props table) for that story set
- [ ] move all stories to CSF
- [ ] remove `addon-info` and move all sources to Docs

**Comment by markov00** [comment]
done
