### ISSUE TITLE
Move away from travis ci

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#575]
Complete the migration from travis ci to kibana-ci. The kibana-ci is much more scalable and faster, especially considering some of the other team's jobs on travis take over 22 HOURS!!!! 😮 

![image](https://user-images.githubusercontent.com/19007109/75269326-59c97880-57be-11ea-8bbd-ff9fef40755c.png)

All pr checks are run in `kibana-ci` already but the branch builds are only run in travis which publish the package to npm.

### Tasks
- [ ] Remove travis-ci check from prs
- [ ] Implement branch builds in `kibana-ci` may need to request changes from infra team
- [ ] Implement [status checks](https://developer.github.com/v3/repos/statuses/) for each test to better understand what is failing. _(optional)_

**Comment by nickofthyme** [comment]
@markov00 I think this is closed by https://github.com/elastic/elastic-charts/pull/854 right?
