### ISSUE TITLE
[meta] Lens use of partition charts

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#612]
Trying to organize the feedback that we've given about pie and treemap charts into one place

Minimum expectations:

* [ ] Tooltip scrollbar bug #596 
* [ ] Legend for first layer to show category colors #532
* [ ] Color contrast by luminance #606 

Nice to have:

* [ ] Tooltip to show field + value #532 
* [ ] Nested legend #223 
* [ ] Better label placement #599 
* [ ] Tiny slices should be grouped during hover #381 
* [ ] Labels per group in treemaps #611 

For developer friendliness:

* [ ] Color theming #610

**Comment by monfera** [comment]
@wylieconlon upon today's release of #652, I split one row and checked a couple of boxes in the Description todo list, as the PR didn't address everything (can't be marked Closed)
