### ISSUE TITLE
Preparation for TSVB timeseries chart replacement

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#64]
This issue keeps track of the tasks required to replace completely the Kibana TSVB charts with the `elastic-charts`:

**Feature parity**

- [x] `DONE` Series specific styling (line width, opacity) #138 PR #170
- [x] `DONE` Handle band area charts (used on percentile band mode) #144 PR #157 
- [x] `DONE` Add last bucket value on the legend #143 PR #155
- [x] `DONE` Fix for time scales in different time zones #130 PR#151
- [x] `DONE` Handle/Test negative values in stacked area charts  #135 PR #149 
- [x] `DONE` Add annotation line #81 PR #126 
- [x] `DONE` hide in legend (hide that series from the legend) #137 PR #147 
- [x] `DONE` Add a separated name props on each series #136 PR #142
- [x] `DONE` Display orphan data points on line/area series #63 PR #114
- [x] `DONE` [Add external custom colour from spec props](#39) #39 PR #95
- [x] `DONE` Crosshair and vertical/horizontal cursors #80 #58  PR #96
- [x] `DONE` Scale data to specific domain #86 PR #98
- [x] `DONE` Add filter in/out series only action to listeners) PR #51
- [x] `DONE` Add hide/show series chart internals) PR #51
- [x] `DONE` Add hover/click event for each legend series PR #51
- [x] `DONE` Add color picker for each legend series #23 PR #51

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Closing this issue as the feature parity is complete.
I've moved the TSVB cross issue to its own ticket: https://github.com/elastic/elastic-charts/issues/178
