### ISSUE TITLE
Preparation for Stack Monitoring chart replacement

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#65]
Stack monitoring team will use the new charts.
They use mainly multi-line charts with few line series (~4 to 5 series max from a first check).

Feature parity:
- [x] Merge interaction on multiple type/series charts: crosshair (issue #80)
- [x] Add annotation lines (like current time marker) (issue #104)
- [x] Externally controlled/synched annotations/crosshair (issue #83)
- [x] Hovered value appears on legend item

**Kibana Cross Issues**
- [x] https://github.com/elastic/kibana/issues/29010
- [x] https://github.com/elastic/kibana/issues/28471
- [x] https://github.com/elastic/kibana/issues/27786
- [x] https://github.com/elastic/kibana/issues/25525
- [ ] https://github.com/elastic/kibana/issues/23839
- [x] https://github.com/elastic/kibana/issues/20184
- [x] https://github.com/elastic/kibana/issues/18310
- [x] https://github.com/elastic/kibana/issues/18247
- [x] https://github.com/elastic/kibana/issues/18228
- [x] https://github.com/elastic/kibana/issues/18160

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present
