### ISSUE TITLE
[meta] Vislib chart replacement

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#66]
📦 Meta issue for [Vislib replacement project](https://github.com/elastic/elastic-charts/projects/8)

### Bugs
- [x] Right Axis rotation pushes label off chart #673
- [x] Add dash style to `AnnotationLine.style.line` #687
- [x] Missing values default to arbitrary value when stacked #680

### Missing features required by vislib
- [x] Allow using ordinal scale type as fallback with `AreaSeries` #678
- [x] Update UI for local toggle and global toggle with color picker UI #717
- [x] Add domain `Bounds margin` on y domain #706
- [x] hide axis but show gridlines #714
- [x] hide axis labels/ticks #714
- [x] Truncate axes labels to specific width #713
- [x] Enable stack offsets for wiggle and silhouette #715
- [x] Allow formatted mark accessor labels #775 (related to #615)
- [x] Multiple charts/Split charts/Small Multiples #500

### Issues with workarounds
- [x] Axis formatter should default to global Axis #676
- [x] Using `stackAsPercentage` on `LineSeriesSpec`
- [x] Show default highlighted radius with hidden dots #679

### High Priority
- [x] Dot size based on point data #533 
- [x] Add color picker render prop #538, #545
- [x] Allow `xAccessor` as a function #551
- [x] Add series label settings to show full series label #539  ~Add `groupIdAccessor` #537~
- [x] Add padding between bar series clusters
- [x] Scatterplot (the current vislib implementation is a line chart without the line)
- [x] Scale data to bounds
- [x] Add annotation lines (like current time marker)
- [x]  Display orphan data (show point when we have intermitted data) (issue #63)
- [x] Add external custom colour from spec props (issue #39)  (PR #51)
- [x] Add filter in/out series (only action to listeners)  (PR #51)
- [x] Add hover/click event for each legend series (PR #51)

**Kibana Cross Issues**

https://github.com/elastic/kibana/issues/56143
