### ISSUE TITLE
Linting configuration changes

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#702]
## List of anomalies

- [x] conflicting rules `typescript-eslint/member-ordering` and `react/sort-comp`
- [x] `max-len` rule not auto fixable.
- [x] Switch back to prettier for indenting
- [ ] eslint formatOnSave vscode configuration (eslint/indent vs eslint/prettier)

**Comment by markov00** [comment]
I think we could split the configuration in two:
- one with fewer restrictions, fewer warnings and fewer errors that we can run quickly and can run unnoticed on every file save
- one with more restriction that one ever X someone can pick up and correct the code in a single PR

I'd like to note also that we should consider the running speeds of each rules using:
`TIMING=1 yarn lint`
this will give us a better idea of the time spent on each rule and we can disable long-running rules that are not strictly necessary.
This is an example of the output:
```
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
import/no-restricted-paths              | 15176.153 |    28.1%
@typescript-eslint/no-floating-promises | 11292.930 |    20.9%
import/namespace                        |  5147.231 |     9.5%
indent                                  |  2864.589 |     5.3%
@typescript-eslint/no-misused-promises  |  2157.196 |     4.0%
react/no-unknown-property               |  1325.769 |     2.5%
react/prefer-stateless-function         |  1045.864 |     1.9%
react/void-dom-elements-no-children     |   692.260 |     1.3%
@typescript-eslint/unbound-method       |   689.988 |     1.3%
import/no-unresolved                    |   611.144 |     1.1%
error Command failed with exit code 1.
```
