### ISSUE TITLE
[meta] Merge the vislib replacement

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#734]
Tasks:
- [x] We should merge the vislib replacement https://github.com/elastic/kibana/pull/78154 in `7.11` under a feature flag:
    - `on` by default on master
    - `off` on 7.x
- [ ] ~ask to whitelist this flag on cloud (I'm not 100% sure if we should turn it `on` on cloud as @timroes suggested, as some features like trellis are not implemented and can cause various visualization to fail, it's easier for Cloud to turn it off but this can cause an increase of support ticket for this)~
- [x] Write an email announcement to describe the changes and avoid receiving issues on known limitations (trellis, streamgraph aka wiggle/silhouette)

**Comment by markov00** [comment]
@nickofthyme I think we can close this right?

**Comment by nickofthyme** [comment]
Yeah I think so. I'm not 100% sure about the second task and if we need to do something on our end.

**Comment by markov00** [comment]
All good, I think kibana-app team will ask that for the next release
