### ISSUE TITLE
[meta] Legend enhancements

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#858]
This issue tracks the planned activities for 7.11 release related to enhancements of the `Legend` component. This list is not the definitive one and can change during the 7.11 timeframe

- [x] Bad legend sizing with long showLegendExtra values - Ordinal #811
- [x] Make legend in charts selectable #710
- [x] Keyboard navigation for legend (beta) #613
- [ ] Legend positioned inside the charts #861
- [ ] Allow a configurable title of the legend #862
- [x] Partition charts with Legend support doesn't work with `showLegendExtra` #638
- [ ] Legend item text color #881

**Comment by markov00** [comment]
closing this in favor of https://github.com/elastic/elastic-charts/issues/580
