### ISSUE TITLE
[meta] Simplified XY axis chart interactions

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#859]
This issue tracks the activities related to the simplification of interactions on the XY axis chart:

- [ ] Option to snap to data point boundary on brushing #851
- [ ] Enable click on the whole bucket #846
- [ ] Highlight a selected bucket #845
