### ISSUE TITLE
[meta] Data sorting

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#860]
This issue tracks the efforts to improve the current ability to sort data at various levels: sorting on scales, on rendering order, on legend, tooltip

- [ ] Sort DataSeries #795
- [ ] The order of the series in the tooltip does not match the legend #303
- [ ] Enable sortIndexAccessor on SeriesSpec #160
- [ ] Allow greater control over layer rendering order #674
