### ISSUE TITLE
Roadmap 7.1

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#87]
# Planned tasks

[GitHub project](https://github.com/elastic/elastic-charts/projects/4)

3 workstreams are planned for the roadmap toward 7.1. 
The priority order of each task is the following:

### 1. Assist teams with new chart integration

- [ ] Future parity of the library to TSVB timeseries and Discovery
- [ ] support EPAM team to replace the TSVB timeseries (line, bar, area)
- [ ] replace Discovery barchart by chart team

### 2. Test and docs

- [ ] increase test coverage (snapshot testing / visual regression testing)
- [ ] increase quality of documentation (add better description of chart usage and configuration)

### 3. General features

- [ ] basic chart exporting to PNG (dependency of `reporting` roadmap for 7.2)
- [ ] showing value labels on chart without hover

# Dependencies

The `reporting` team will start client-side export of ES chart in 7.2. We have to prepare the field with some basic functionalities to export PNG from charts.
