### ISSUE TITLE
[meta] Heatmap gaps in comparison to kibana heatmap

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#875]
Gap comparison between the Kibana legacy heatmap and the current ECH heatmap implementation

## Planned for 8.1 (experimental):

- [x] #1221
- [x] #1168 https://github.com/elastic/kibana/pull/202143

## Planned for 8.x (GA):

- [x] #1486
- [x] #1484 
- [x] #1485
<img width="400" alt="Screenshot 2020-10-20 at 12 46 36 PM" src="https://user-images.githubusercontent.com/17003240/96576712-3ae29e00-12db-11eb-9dec-3d7b4ef2c878.png">

## Done:
- [x] https://github.com/elastic/kibana/issues/14291
- [x] I can see that the legend can also have color picker. Is it applicable for heatmap too?
- [x] ~~Customize the color of the cell labels~~ Update: not supported for now, we will wait for users' feedback
- [x] ~~Rotate cell labels~~ Not needed, the font size could be responsive. We had this feature for readability cc @markov00 
<img width="400" alt="Screenshot 2020-10-20 at 12 48 06 PM" src="https://user-images.githubusercontent.com/17003240/96576734-45049c80-12db-11eb-993c-264f4e6d60ae.png">

**Comment by markov00** [comment]
>  I can see that the legend can also have color picker. Is it applicable for heatmap too?
You can probably add a color picker as done here: https://elastic.github.io/elastic-charts/?path=/story/legend--color-picker and use the callback color to update the chart configuration

**Comment by markov00** [comment]
@stratoula could you please check with Alona and in the current Kibana repo the reason (if any) for the existence of the `Rotate cell labels` feature? I'm wondering if that was implemented as a workaround to improve the readability of values with tall but thin cells. I'd like to understand if we can do something better then that in this case: like reducing the font size, or something similar

**Comment by stratoula** [comment]
> @stratoula could you please check with Alona and in the current Kibana repo the reason (if any) for the existence of the `Rotate cell labels` feature? I'm wondering if that was implemented as a workaround to improve the readability of values with tall but thin cells. I'd like to understand if we can do something better then that in this case: like reducing the font size, or something similar

Sure Marco, I will update the issue when I have feedback on this.
