### ISSUE TITLE
[meta] Elastic-charts gaps in comparison to kibana timelion

### ISSUE THREAD

**Issue by VladLasitsa** [elastic/elastic-charts#878]
Below I provide a list with possibilities of timelion which elastic-charts doesn't have:

- [x] `DONE` #861 PR #1031  Possibility to set position for legend by corners of visualization (ne - north east corner, nw, se, sw). Also the legend position inside visualization but elastic-charts provides positions only outside. You can see below screenshot where I set position for legend as 'se' (south east).
![image](https://user-images.githubusercontent.com/16915480/97305993-dbeacf00-186e-11eb-847c-76a2d98a146b.png)

- [x] `DONE`  #1158  Possibility to set count of columns for legend. You can see below screenshot where I set count of columns as 2.
![image](https://user-images.githubusercontent.com/16915480/97305751-96c69d00-186e-11eb-8991-0eb4ac283477.png)

- [x] `DONE` Possibility to set symbol for points. We can choose symbol for points from this list ['triangle', 'cross', 'square', 'diamond', 'circle'].  You can see below screenshot where I set symbol for points as 'diamond'. #987 PR #988 
![image](https://user-images.githubusercontent.com/16915480/97306437-8a8f0f80-186f-11eb-83b0-a35f8ddf8956.png)

- [x] `DONE` #497 Possibility to set width of the bars.
![image](https://user-images.githubusercontent.com/16915480/98540040-57e90c00-229e-11eb-9605-891d812bb3b7.png)

**Kibana Cross Issues**

https://github.com/elastic/kibana/issues/79984

**Checklist**

Delete any items that are not applicable to this feature request.

- [ ] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Done, available in [v29.2.0](https://www.npmjs.com/package/@elastic/charts/v/29.2.0)
