### ISSUE TITLE
[Goal] Replace Kibana TSVB Goal with es-charts

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#961]
**Is your feature request related to a problem? Please describe.**
I am working on replacing the TSVB goal chart with the es-charts goal and I can see some features that are not supported so I am creating this issue in order to discuss them.

- [x] #1239 

So far I have managed to replace it and it seems really good. I have set the target and actual to 0 in order to look more with the current TSVB implementation but I am not sure if this is correct. I think we should discuss this.

Current implementation example: 
<img src="https://user-images.githubusercontent.com/17003240/103643884-1a32f780-4f5e-11eb-94d0-1a01670fe30c.png" width="500">

Elastic charts implementation example (target 0):
<img src="https://user-images.githubusercontent.com/17003240/103643838-025b7380-4f5e-11eb-9607-615c51e7ac89.png" width="500">

Elastic charts implementation example (target set to value):

<img src="https://user-images.githubusercontent.com/17003240/103644035-5bc3a280-4f5e-11eb-9ec1-93f4844eeb0e.png" width="500">

- [x] #1240

The first thing that I notice is that when I choose to display my chart s half-circle there is an empty space below that if it didn't exist my chart would appear bigger. I assume that this happens because I have the `labelMajor` and `labelMinor` to empty string. Can I choose that I don't want to be rendered in order to gain this space?

- [ ] #1244

 As you can see on the screenshot below the user can change the `Inner Line width` (it is the border line), the `Gauge line width` (the width of the goal line) and the text color. I think that changing the Inner line width is not so important but the other two maybe they are. Wdyt?
 <img src="https://user-images.githubusercontent.com/17003240/103644550-384d2780-4f5f-11eb-8f7d-7700c221e855.png" width="500">

- [x] #1235 

When I have multiple goal charts configured to be displayed as circle, I need to place an additional label to display the split term. It is not displayed very well, and the same thing occurs when I have a title that is quite big (see screenshots below).  I think that the texts should be somehow responsive, any ideas here?

<img src="https://user-images.githubusercontent.com/17003240/103644904-d0e3a780-4f5f-11eb-9130-7a634f6e6419.png" width="500">

<img src="https://user-images.githubusercontent.com/17003240/103645513-c4ac1a00-4f60-11eb-9a65-960e107f34bb.png" width="500">

- [x] #1243

**Kibana Cross Issues**
Kibana related issue [here](https://github.com/elastic/kibana/issues/82729)

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by stratoula** [comment]
No with the bullet chart. When I created the issue it was mostly for replacing it with the EC goal (same look and feel with the TSVB one). 

When we added the TSVB to Lens conversion the transition goes to Lens new metric which also makes sense. I think that possibly we should not do anything but rather prioritize the deprecation of TSVB but happy to hear your thoughts!

**Comment by nickofthyme** [comment]
That's good with me, I think the new bullet is too much of a divergence from the current TSVB chart anyways. As mentioned in the sync, I think having the ability to convert existing TSVB goal/gauge to Lens Metric then to Lens Bullet is a nice transition.

Closing unless otherwise objected.
