### ISSUE TITLE
Dependency upgrade

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#998]
- [ ] upgrade node to 14 #997 
- [ ] upgrade EUI
- [ ] upgrade webpack (to latest 4), and related packages
- [ ] storybook (addon-info needs to be replaced, the upgrade should be smooth just remember to override the page style - [ ] padding for the story due to an additional 20px padding in SB6)
- [ ] remove unused/deprecated deps like core-js, babel-polyfill, @elastic/ghithub-check
- [ ] breaking-change: compile everything on ES2020 (the most updated target version compatible with most desktop browsers)
